apiVersion: core.springclouddataflow.crossplane.io/v1alpha1
kind: Application
metadata:
  name: app-1
spec:
  forProvider:
    name: "App001"
    type: "task"
    version: "v1.0.0"
    uri: "docker://hello-world:v1.0.0"
    bootVersion: "2"
    defaultVersion: true
  providerConfigRef:
    name: local-springclouddataflow-instance-config
