apiVersion: core.springclouddataflow.crossplane.io/v1alpha1
kind: Application
metadata:
  name: app-1
spec:
  forProvider:
    name: "App001"
    type: "task"
    version: "3.0.0"
    uri: "docker:springcloudtask/timestamp-task:3.0.0"
    bootVersion: "2"
    defaultVersion: true
  providerConfigRef:
    name: local-springclouddataflow-instance-config
---
apiVersion: core.springclouddataflow.crossplane.io/v1alpha1
kind: Application
metadata:
  name: app-2
spec:
  forProvider:
    name: "App002"
    type: "source"
    version: "1.0.0"
    uri: "docker:springcloudtask/timestamp-task:3.0.0"
    bootVersion: "2"
    defaultVersion: true
  providerConfigRef:
    name: local-springclouddataflow-instance-config
---
apiVersion: core.springclouddataflow.crossplane.io/v1alpha1
kind: Application
metadata:
  name: app-3
spec:
  forProvider:
    name: "App003"
    type: "sink"
    version: "1.0.0"
    uri: "docker:springcloudtask/timestamp-task:3.0.0"
    bootVersion: "2"
    defaultVersion: true
  providerConfigRef:
    name: local-springclouddataflow-instance-config
