apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: debug-config
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              args:
                - --debug
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-keycloak
spec:
  # if you want to use the official provider-keycloak version, use this instead
  #package: xpkg.upbound.io/crossplane-contrib/provider-keycloak:v1.6.0
  package: registry.k3d.localhost:5000/provider-keycloak:provider-keycloak-v5-pre.1.0.1.xpkg
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  runtimeConfigRef:
    name: debug-config