apiVersion: v1
kind: Secret
metadata:
  name: provider-keycloak-config-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "client_id": "admin-cli",
      "url": "http://my-keycloak-keycloakx-http.default.svc.cluster.local",
      "base_path": "/auth",
      "realm": "master",
      "username": "admin",
      "password": "admin"
    }