apiVersion: v1
kind: Secret
metadata:
  name: provider-keycloak-config-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "client_id": "admin-cli",
      "username": "admin",
      "password": "admin",
      "url": "http://keycloak-keycloakx-http.default",
      "base_path" : "/auth"
    }