apiVersion: keycloak.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: local-keycloak-instance-config
  namespace: crossplane-system
spec:
  credentials:
    secretRef:
      key: credentials
      name: provider-keycloak-config-creds
      namespace: crossplane-system
    source: Secret