apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: IdentityProviderMapper
metadata:
  name: kc-oidc-idp-username-mapper
spec:
  forProvider:
    realm: "test"
    name: "usernamemapper"
    identityProviderAlias: "myoidcidp"
    identityProviderMapper: "oidc-username-idp-mapper"
    extraConfig: 
      syncMode: "INHERIT"
      target: "LOCAL"
      template: "$${CLAIM.preferred_username}"
  providerConfigRef:
    name: local-keycloak-instance-config
