apiVersion: v1
kind: Secret
metadata:
  name: provider-grafana-config-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "url": "http://my-release-grafana.default",
      "auth": "admin:password"
    }